version: '3.8'

services:
  app:
    build: .
    ports:
      - "7860:7860"
    env_file:
      - .env
    #volumes:
    #  - nltk_data:/app/nltk_data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7860/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped

volumes:
  nltk_data:

networks:
  app-network:
    driver: bridge 