services:
  app:
    extends:
      file: docker-compose.yml
      service: app
    depends_on:
      ollama:
        condition: service_healthy
        required: true
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434

  ollama:
    image: ollama/ollama:${OLLAMA_HARDWARE:-latest}
    ports:
      - "11434:11434"
    env_file:
      - .env
    environment:
      - OLLAMA_BASE_URL=${OLLAMA_BASE_URL:-}
    volumes:
      - ollama_data:/root/.ollama
      - ./docker/ollama/entrypoint.sh:/entrypoint.sh
    networks:
      - app-network
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    tty: true
    #restart: always
    entrypoint: ["/usr/bin/bash", "/entrypoint.sh"]
    healthcheck:
      test: 
        - "CMD-SHELL"
        - |
          test -f /tmp/ollama_ready && \
          bash -c '</dev/tcp/localhost/11434'
      interval: 10s
      timeout: 10s
      retries: 100
      start_period: 10s

volumes:
  ollama_data:
    name: synthetic-data-ollama